server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以任意
        - id: user-service-route
          uri: lb://user-service
          # 路由断言： 可以匹配映射路径
          predicates:
            - Path=/api/user/**
          filters:
            #表示过滤1个路径，2表示两个路径
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true